version: '3.7'
services:
  selenoid1:
    image: aerokube/selenoid:latest-release
    container_name: selenoid1
    networks:
      - selenoid1
    hostname: selenoid1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/user/selenoid_python/browsers.json:/etc/selenoid/browsers.json:ro
    command: -container-network=selenoid1 -limit 10
  selenoid2:
    image: aerokube/selenoid:latest-release
    networks:
      -  selenoid2
    hostname: selenoid2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/user/selenoid_python/browsers.json:/etc/selenoid/browsers.json:ro
    command: -container-network=selenoid2 -limit 10
  ggr:
     image: aerokube/ggr:1.7.2
     networks:
     - selenoid1
     - selenoid2
     hostname: ggr
     depends_on: [selenoid1, selenoid2]
     volumes:
     - /etc/grid-router:/etc/grid-router:ro
     command: -guests-allowed -guests-quota "test" -verbose -quotaDir /etc/grid-router/quota
  ggr_ui:
    image: aerokube/ggr-ui:latest-release
    hostname: ggr_ui
    networks:
    - selenoid1
    - selenoid2
    volumes:
    - /etc/grid-router/quota/:/etc/grid-router/quota:ro
    depends_on: [ggr]
  selenoid_ui:
    image: aerokube/selenoid-ui:latest-release
    hostname: selenoid_ui
    networks:
    - selenoid1
    depends_on: [ggr_ui]
    command: --selenoid-uri http://ggr_ui:8888
  nginx:
    image: nginx:latest
    depends_on: [ggr, selenoid_ui]
    volumes:
    -  /root/selenoid/nginx/:/etc/nginx/conf.d:ro
    hostname: nginx
    networks:
    - selenoid1
    ports:
      - 80:80

networks:
  selenoid1:
    name: selenoid1
    external: true
  selenoid2:
    name: selenoid2
    external: true
